---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: present

- name: Install common packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - patch
    - lsof
    - screen
    - vim
    - git
    - iotop
    - iftop
    - htop
    - atop
    - libcgroup-tools
    - bind-utils
    - strace

- name: Ensure services are enabled + started
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - atop

- name: yum-autoupdate removal
  yum: name=yum-autoupdate state=absent
